### ISSUE TITLE
dude come on what is your problem:/ 

### ISSUE THREAD

**Issue by hiradexo** [skidmaster69420/discord-tokens#1]

**Comment by skidmaster69420** [comment]
Hello there.

Thank you so much for asking! The FBI is actually after me and is seeking 10k from me. So if you can help me with that, let me know. Because if I don't transfer the amount in less than 3 weeks, then my cats will all be shoot dead! AND YOU'D BE RESPONSIBLE! The cats have all been turned gay, because I couldn't pay up which has lead to severe depression on my side. Also, they kicked me out of my local homeless shelter because they thought that the cats smelled too much of weed. And hear me out, THOSE CATS lived in the WALLS. It wasn't even my fault to begin with! Sure, I feed them drug pills every 10 minutes, BUT HOW IS THAT MY FAULT? They asked me for drugs, and I supplied. And now the FBI is after me, like... what's their deal? You know. I mean sure, I may have violated several thousand conduct rules, but I don't care! Hear me out, pissing on the empire state is my constitutional right! Sure, the people got wet, but rain does the same! Oh where was I... Right, the CIA! The CIA is actually also after me because I wrote "The CIA sucks" on my local homeless shelter walls, but I mean it's true! Oh and the cats? THEY OWE ME MONEY, 20k TOTAL! So I actually am required to save them in order to get my money back. Also should I consider getting rid of my non-illegal amount of cocaine? I mean it's legal, in a way. And you could buy it.... I forgot where I was again, you have to forgive me, I am suffering from short-term memory issues because I read your issue, it drained me of brain capacity.
