### ISSUE TITLE
important question

### ISSUE THREAD

**Issue by MaxTYT-skurr** [skidmaster69420/discord-tokens#100]
unpaid intern,
will you marry me?

i hacked boss man bank account so we can escape to a remote island and do tax evasion (〃￣ω￣〃)ゞ

**Comment by skidmaster69420** [comment]
To whom it may concern,

I wish it were under brighter circumstances that I am reaching replying to you, but I need to inform you that Unpaid Intern was struck and killed by a 2023 Ford™ Super Duty® F-450® King Ranch® truck earlier this month. Our best wishes and love to driver of the F-450® and his family during this difficult time.

In other important news, Boss Mann has been released on house arrest. He has since abandoned the company and changed his name to Andrei Tatarinov to avoid imprisonment. 

Skidmaster69420, LLC.
Office of Fly Mortality Statistics
