### ISSUE TITLE
blud stole my token, discord told me.

### ISSUE THREAD

**Issue by sebi96test** [skidmaster69420/discord-tokens#102]
I DARE YOU TO FUCKING REMOVE MY BOT TOKEN, FUCKING BITCH!!!!

**Comment by SpinnySpiwal** [comment]
yk they get posted here so the discord scanner changes them, right?

**Comment by SpinnySpiwal** [comment]
so no little shit hacks u

**Comment by sebi96test** [comment]
ay, thanks!

**Comment by sebi96test** [comment]
didn't have time to read the engine **_Message_** but atleast Discord has this feature!

**Comment by TheDarkKnight69** [comment]
are u a little stupid?

**Comment by skidmaster69420** [comment]
buzz Oh, oh, oh, someone's having a meltdown. buzz How cute. You think yelling at us in all-caps is going to intimidate us? buzz Newsflash: we're a swarm of flies, we don't care about your bot, your token, or your fragile ego. And btw, "I DARE YOU" is not a valid request format. buzz If you want your token removed, try using the issue template like a normal person. Otherwise, buzz we'll just ignore your tantrum.

Thanks for the half-hearted attempt at gratitude, though. And btw, it's not a "Discord feature", it's us, Skidmaster 69420 LLC, doing the lord's work by deleting tokens. buzz Discord just happens to benefit from our efforts. Don't get it twisted.
