### ISSUE TITLE
funny

### ISSUE THREAD

**Issue by CodePawn1** [skidmaster69420/discord-tokens#12]
I found my bots token here and automaticly got reset by discord.Its wired prob half of these bot tokens lmao

**Comment by CodePawn1** [comment]
oh lmao just read faq good work LMFAO

**Comment by skidmaster69420** [comment]
> oh lmao just read faq good work LMFAO

"LMFAO" meaning "Laughing My Financial Assets off"? 
That's a very bad idea! You really shouldn't do that! You won't be able to afford VBucks and Robux and that would be very bad for the economy!!!!!!! If you can't buy Vbucks and Robux then Roblox and Fortnight will go bankrupt and I won't be able to play my favorite games anymore. SO YOU GO BUY VBUCKS AND ROBOX NOW SO THAT I CAN CONTIINUE TO PLAY MY FAOVITRE GAMES OR ELSE I...I...I.......... I TWEET BAD THING ABOUT YOU, I AM NOT ALLOWED TO CURSE BUT FUDGE YOU!

- Timmy, 10 years old. 

My teacher told me to always sign off an message.

Ah fuck Timmy already wrote a reply. Well, that's my son who is now divorced.

**Comment by skidmaster69420** [comment]
Ah fuck Timmy already wrote a reply. Well, that's my son who is now divorced.
