### ISSUE TITLE
Stop stealing my discord bot's token

### ISSUE THREAD

**Issue by thirsty-12** [skidmaster69420/discord-tokens#13]
Remove the files immediately please

**Comment by Whanos** [comment]
You put your token publicly somewhere, dummy. This invalidated your token so someone can't be malicious with it. You're welcome

**Comment by FrancyPro** [comment]
![Uploading Screenshot_2022-08-30-13-15-43-84_572064f74bd5f9fa804b05334aa4f912.jpg…]()

**Comment by FrancyPro** [comment]
![Screenshot_2022-08-30-13-15-43-84_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/92643600/187425555-cc1883ec-61f6-49d4-ab88-bc8da1a6f434.jpg)

**Comment by skidmaster69420** [comment]
Hello there, 

I am an unpaid Intern from Skidmaster69420 LLC, I wish to give you a rather recent example of what happened to me, which is related to what happened to you. 

This happened on Tuesday evening, I was coming home from a Solitaire Crash Course for Beginners, which took 6 hours. Sadly, I didn't understand anything while there. I was walking to my car, exhausted. Sadly, my car was already gone. I believe this is due to my habit, of leaving my keys in my car's ignition. I tried to file a Insurance Report, however I don't know how to do that.  Anyhow, because I left my car unlocked and the key in my ignition, my car was stolen. 

The same could have happened to you, if these trained token vultures didn't take the key (being the token) away and destroyed it. Now you can be thankful that your car (bot) is still with you. Don't leave your token in a public place. It's the same as leaving your car unlocked and the key in the ignition.

Sincerely 
Now carless Intern. 
SKIDMASTER69420 LLC
