### ISSUE TITLE
HAHA

### ISSUE THREAD

**Issue by JacobPOGCHAMP** [skidmaster69420/discord-tokens#15]
i find your replies to the kids crying very amusing, Mr Skidmaster69420, honestly I don't care my bot's token is published on here, but I was wondering if we can talk on discord? I have a few questions to ask. It's fine if not, I honestly love seeing all the kids crying that their bot token is published on here. Most of these are ment for malicious activity but some aren't, like mine which was not ment for malicious activity. Keep up the good work! Discord - kamidere#0001

**Comment by skidmaster69420** [comment]
Dear Jacob Pogchamp,

We have to applaud your family for carrying such a name. However, that aside. We at SKIDMASTER69420 are frankly very confused by your issue. Sadly, it also lead to another one of our Hyper Intelligent Flies, which read at a very high level. To losing its life. It tried to compare your issue to the plays of Shakespeare, Hamilton, CATS, Emoji Movie and most notably Homer. We ask that you attend the funeral and bring an adequate amount of compensation for the fly's 10000 leftover family. We are estimating a total cost of 40.000 Dollars. 

Sadly all children, including you, attending the funeral must pay an upfront cost of 10,00 Dollars because you might disturb the flies mourning their loved one passing on. Also all funeral attendees must attend to all fly funerals held that day. We are estimating a total of 10.000 funerals that day. 

After talking to the flies about your request for "communication" on """Discord""". They explained that it was a platform for Idiots where you can connect with other Idiots. However, I don't know how it works nor can I use it because my Boss is only allowing the Browser for the responses I have to write and Solitare. After I lost Fortnite, Roblox and the critically acclaimed MMORPG FINAL FANTASY XIV that has a free trial up to level 60 including the Heavensward expansion because I leaked company secrets. I lost all methods of communication aside from GitHub. So may I ask you very kindly, in what order do I place the cards in the "tableau" piles?

Yours
Unpaid Intern
SKIDMASTER69420 LLC
