### ISSUE TITLE
half the newgens here don't understand what this repo is

### ISSUE THREAD

**Issue by JacobPOGCHAMP** [skidmaster69420/discord-tokens#16]
half the newgens here don't understand what this repo is, they should be thanking you because they don't understand that any little faggot from uzbekistan can come and take their bot token from whatever public shit they put it on and nuke all the servers that it's in. :)

**Comment by skidmaster69420** [comment]
HOW DARE YOU.

The family of 10000 children flies ARE ALL learning very BAD words from YOU. 
YOU are the reason THEY started using SLURS and PROFANITY. They are now playing FORTNITE and VAPING, They just did an ORANGE justice on my PAUSED screen of SOLITARE while I am still LEARNING how to play SOLITARE. I wish I could PLAY FORTNITE with the flies but NO they are too busy MISBEHAVING because you thought them HOW.

We DEMAND that you pay 10 DOLLARS to the Uzbekstian CHILDREN as repentance for this heinous crime of teaching the files TERRIBLE BEHAVIOR.

NOT SINCERELY
UNPAID INTERN
SKIDMASTER69420 LLC

**Comment by Whanos** [comment]
Mashallah

**Comment by JacobPOGCHAMP** [comment]
OK I AM VERY SORRY, I HAVE NOW DONATED 10 DOLLARS TO FEEDING CHILDREN IN BROKEN HOMES IN UZBEKISTAN

I AM VERY SORRY AND I HOPE THAT THE UZBEKISTANIE CHILDREN CAN FORGIVE ME

**Comment by skidmaster69420** [comment]
Hello there,

Unfortunately, to respect the passing of Her Majesty Queen Elizabeth II, Skidmaster69420 Ltd. will not respond to your issue at this time.

Thank you for your understanding.

Department of Mourning (Formally, Department of Fly Mourning)
Skidmaster69420 Ltd.
A division of Skidmaster69420, LLC
