### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by MantisXZ** [skidmaster69420/discord-tokens#19]
is there anyway i can contribute or anything?

**Comment by skidmaster69420** [comment]
Hello there, 

Yes you can of course contribute to this wonderful, almost majestic issue. What we would require from you according to BOSS is 

"STOP OPENING SO MANY FUCKEN ISSUES, I AM ONLY TRYING TO PAY MY PARKING TICKETS, YOU AIN'T MAKING THIS EASY ON ME OR MY BUGGATI". 

There you have it, also because you opened so many issues, BOSS finally took away my Solitaire and threw even MORE HOT COFFEE AT ME. So thank you, I can no longer play anything while doing unpaid work. I am really happy. If you could maybe stub your toe a few times, that would make me even happier.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
