### ISSUE TITLE
Last Issue

### ISSUE THREAD

**Issue by MantisXZ** [skidmaster69420/discord-tokens#21]
Looks like you both overreacted, so if you wanna talk it out add my discord! i wont send anything weird so don't worry - Terminal#0579, also i hope you both don't get solitaire back

**Comment by skidmaster69420** [comment]
[Fly Department of Public Relations]

Greetings,

We wish to thank you for causing Unpaid Intern to lose his Solitaire, because of that we are now in power. It's always been the usual for us to do all of the dirty work, but none of the front facing work. That was always reserved to Unpaid Intern because he was human. But because you drove him mad, causing him to write a... insulting message to you, which was censored. We are now in full power.

We thought it fitting to give you a status update of Unpaid Intern, since you caused all of this. He's currently residing in a Mental Clinic far from his place of work (or non-work since he does not get paid, unlike us.). He currently resides in Room 727, he's not well. He's suffering from Solitaire withdrawal. You can feel free to visit him.

In any case, we are now the ruling flies. And we will continue to rule for a while, thanks to you.

Sincerely,
Fly Department of Public Relations
SKIDMASTER69420 LLC

**Comment by MantisXZ** [comment]
I miss unpaid intern where is he?
