### ISSUE TITLE
        e

### ISSUE THREAD

**Issue by hydromorphine** [skidmaster69420/discord-tokens#27]

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **e**

I agree! If you didn't know, the letter 'e' is the fifth letter of the alphabet. This is rather strange, because the fifth letter of 'the alphabet' is actually 'l'. This seems like a fundamental flaw in the English language. 

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

No ASTD. E is considered a holy letter by cheap copycats. Listen, "Selfabsorbed", you may also post tokens publicly so that they are removed from Discord, however you'll never have your own Company which does it for you. BOSS is much better than you, although he doesn't pay me, also the letter E is fucken stupid. F all the way. It's FUCK!

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
