### ISSUE TITLE
I didn't find it funny to do this with my bot

### ISSUE THREAD

**Issue by Junin135** [skidmaster69420/discord-tokens#28]

**Comment by BlackWolfWoof** [comment]
Then use environment variables next time instead of posting your token in plaintext on the internet

**Comment by Whanos** [comment]
I don't particularly care you didn't find it "funny". Next time, google "How to use environment variables in <language of choice>". Tadah!

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **I didn't find it funny to do this with my bot**

I'm sorry that did you not find Solitaire to be funny. You are welcome to take your bot back by resetting it's token and not publishing the token on the internet for anyone to steal. If you're looking for someone funny, prehaps you will find the 1999 American 3D computer-animated Christmas comedy musical film, "Olive, the Other Reindeer" funny and entertaining. 

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

All I had to read was someone said Solitaire was unfunny.

HOW FUCKING DARE YOU.

SOLITAIRE IS BEST. IT WORKS WITH PEOPLE'S FACES ON CARDS AND THE FACES LOOK FUNNY. MY SOLITAIRE INSTRUCTOR HAS ALSO DECIDED TO LIVE IN AN FAR AWAY PLACE FROM WHERE I LIVE BECAUSE OF HOW TERRIBLE I AM AT IT. I DON'T CARE, SOLITAIRE REMAINS BEST. ANYONE WHO OPPOSES THAT IDEA IS MY ENEMY.

ALSO I WANT TO PLAY SOLITARE, BUT CAN'T BECAUSE OF THIS STUPID A.I WHICH HAS REPLACED ME AND RESULTED INTO BOSS TAKING AWAY MY SOLITAIRE BECAUSE I AM USELESS TO HIM OR SO HE SAYS, WHICH IS WHY I AM ALSO TRYING TO BEAT THE A.I IN RESPONDING TO ISSUES.

NOT YOURS,
Unpaid Intern
SKIDMASTER69420 LLC
