### ISSUE TITLE
Why is my bots token in here and luckly discord reset it

### ISSUE THREAD

**Issue by Nightyourmom** [skidmaster69420/discord-tokens#34]

**Comment by Peter-Maguire** [comment]
The whole purpose of putting them in here is so that Discord resets them

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **Why is my bots token in here and luckly discord reset it**

Hi there, your bot token has been located by our token vultures attempting to locate Christmas gifts for orphaned flies on the internet. However, these vultures located too many tokens and made a massive pile of tokens on top of the flies, killing thousands. Due to the disaster, we have decided to donate the pile of fly courses and tokens that is this repository to Discord. In turn, Discord has decided to destroy and reset your bot token because it was infected with Christmas Malaria. 

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

Christmas Malaria is a serious problem, it had affected many Discord Servers and Token Vultures, we have taken a step to try and reduce any infectious tokens being delivered to Discord HQ.  Merry Christmas and please feel free to donate to the annual Christmas Buggati Fund.

>This response is a legal response according to Paragraph 65 of Health Safety at SKIDMASTER69420 LLC.

Yours, 
Unpaid Intern
SKIDMASTER6940 LLC
