### ISSUE TITLE
This isn't helpping anyone.

### ISSUE THREAD

**Issue by NTechsoftware** [skidmaster69420/discord-tokens#35]
**_If someone is to have their token public online it would be for a reason. Doing this will cause them to be changed and this will just cause annoying problems for people. So just stop because its just annoying for developers._**

**Comment by IMarkoMC** [comment]
Lean how to protect your token and it won't be a issue.

Leaving your token in plain text will result in your server getting nuked and you crying over that

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **This isn't helpping anyone.**
> If someone is to have their token public online it would be for a reason. Doing this will cause them to be changed and this will just cause annoying problems for people. So just stop because its just annoying for developers.

Hello there, all smart people believe (correctly) that this repo is helping people. Only cringe people would think otherwise. We are giving you the best Christmas gift you could ask for: education. We don't really care that you may want to post your token online-- you're an idiot. By posting your token on the internet, please can hack your Discord bot and use it to send viruses, invitations to Satanic cults, or NFTs. You should be lucky Jesus Christmas and Santa Claus found your Discord token instead of Elon Musk, Satan, or The Artist Formerly Known As Prince. For many, God is the greatest annoyance because He has the answers for which we have no answer.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by NTechsoftware** [comment]
> 
It was an old bot that I was just testing with. It's only in a tests server. I do have a brain!

**Comment by skidmaster69420** [comment]
Hello there,

We are glad that you have confirmed with yourself that you have a brain, however it must be said that the Idea that leaving such a bot be is okay, is stupid. Since your bot could get taken over and used for malicious purposes including but not limited to: stealing discord accounts, phishing, etc. And it would all be done with your bot. This repository is simply ensuring that this does not happen. If you want it explained simple:

Your token is your car key, sure we could let your car (bot) be stolen and let the malicious driver run people over with it, or we could destroy your car key and let you create a new one preventing any and all disaster. 

We are doing it for your sake. We don't mean no harm like disabling your bot because we are bored. We are trying to prevent harm.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
