### ISSUE TITLE
Thank you for taking my token so that my token won’t be scammed and sorry for not knowing why you’re doing this

### ISSUE THREAD

**Issue by Kyosaka-Nekoho** [skidmaster69420/discord-tokens#38]
https://github.com/skidmaster69420/discord-tokens/blob/eea66f74912644fa9c3404f92df8ccbf5faed39e/tokens/12-28-2022
found it thanks to Discord system

**Comment by PRINCE-HERE** [comment]
same xd ( https://github.com/skidmaster69420/discord-tokens/blob/050ad9cac37fd6f319af993f46c504269c6ee07e/tokens/12-29-2022 ) Thanks to Discord

**Comment by Peter-Maguire** [comment]
The whole point of this repo is so that Discord invalidates them so that they can't be used by other people since you left it out in public

**Comment by aerydev** [comment]
yall dum, read the README.md  file###

**Comment by PRINCE-HERE** [comment]
> yall dum, read the README.md file###

The first time I checked this repository, it said something like "can't show files". So I couldn't read what was written in the README.md file. All I could check are the comments and Issues of this repository. I found this issue with the title "How dare you take my boy token". I thought that it's some kind of scam.

**Comment by skidmaster69420** [comment]
Date: 18.12.2022
Hello there,

I am in a HUGE hurry, so let me type this out fast. Thank you very much for apologizing and thanking us for saving your tokens so that we can thank you for thanking us for thanking you. 

Long story short, ignoring a subpoena IS A VITAL MISTAKE. The police is going to be picking me up any second now, and it's NOT going to be a fun experience. I am probably going to be interviewed, they have already taken my Miku figurine hostage. Hence I am being very cooperative. Anyway, that's all I can say for now. Wish me luck.

I just hope that they won't hurt Miku.

Goodbye

Your,!:3$(%=§$=%(&/)§="?)($
Unpaid Intern
SKIDMASTER69420 LLC
