### ISSUE TITLE
Keep working on your bot

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [skidmaster69420/discord-tokens#39]
So I see what you are doing and I fully support! But I just think your bot should look at the code and see what it's doing. All my bot was doing was looking in **MY** discord channel and printing the messages to the console. I *did* have a web hook In there that could have messed up your bot. Thank you for trying to make Discord better and I hope you can get your bot to be more accurate!

**Comment by BubbleBubblePlayz** [comment]
I do also realize that it is a repl of "Scam nitro generator".

**Comment by IMarkoMC** [comment]
>  I hope you can get your bot to be more accurate!

Filtering is not a good idea all around as that opens a window for bad actors to bypass the token deletion and storing your discord bot token in plain text is not in your best interest anyways. You should store your tokens in environment variables

**Comment by skidmaster69420** [comment]
Date: 28.12.2022

Hello there, 

you should really store your tokens in [ENV ](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env) as was recommend above. 

In any case, here's what has happened in the last two days. SKIDMASTER69420 LLC. has mandated a vacation for 4 days for all and any employees. I have also been fired as of yesterday, I no longer work for SKIDMASTER69420 LLC. however my access has not yet been revoked. I am unsure why he hasn't been using this account to try and contact the public. However it seems he's simply to busy running away from authorities that are hunting him due to the Automobile Car Part Manufacturing Ring he leads. 

I am unsure what this means for the future of the company, I'd hate for it to be gone. I mean I am well aware we are under police monitoring, but that was all.

Yours,
Unpaid Intern
