### ISSUE TITLE
LMAO my token was a music bot ☠️☠️☠️

### ISSUE THREAD

**Issue by Zyv0001** [skidmaster69420/discord-tokens#42]
Hey Zyv,
Safety Jim here! It appears that the token for your bot, Ascend has been posted to the internet. Luckily, our token-scanning gremlins noticed, and have reset your bot's token - hopefully before anyone could have maliciously used it!

Your token was found here: https://github.com/skidmaster69420/discord-tokens/blob/7e24599f275475394dd2b28c933433a11aa67375/tokens/01-06-2023

Be more careful in the future, and make sure to not accidentally upload your token publicly!

**Comment by Zyv0001** [comment]
But i like what yall are doing to keep people safe

**Comment by aerydev** [comment]
same

**Comment by wadefield** [comment]
My token was a cancelled bot LMFAOOO 💀

**Comment by ConceptualFear** [comment]
> But i like what yall are doing to keep people safe

Ahhh yes, annoying non-malicious bot users with offlines is totally helping. Maybe you should actually investigate rather than just spamming any token you get ahold of? Hmmmm...it's almost like what you call 'helping" people is really "hurting" people. Imagine that. Offline times are officially down by who knows what percentage. But oh well, I guess in your eyes "the owner can just use the new token, no problem." If so, that case also applies to the malicious ones ;D.

Maaaaybe you could try finding the source and reporting it to Discord! Fuck me that's so much more effective. Spending all your time finding these tokens and you could be spending that time finding the real ones. Damn, that sounds pretty cool. Probably not for you tho.

**Comment by tcprescott** [comment]
@ConceptualFear Or, you know, the user can use this as a valuable learning experience and properly secure their bot's token so bad guys don't use them to do bad stuff.

**Comment by skidmaster69420** [comment]
Hello there,

It's me, Unpaid Intern, it's been a while. Well, I did spend that time in prison after all.
Though I have to say that the prison was very comfortable. Anyway, as others have already lectured you,
I will keep this short. Yeah they released me, said I was too expensive to keep imprisoned. So I am back,
I will be delivering roasts as you are used to.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
