### ISSUE TITLE
worthless

### ISSUE THREAD

**Issue by Linuspro** [skidmaster69420/discord-tokens#46]
discord notified the owner of every bot token listed here and automatically reset the tokens. So yeah, this list is pointless.

**Comment by IMarkoMC** [comment]
> So yeah, this list is pointless.

Do you know how to read?
Seems like your IQ is too low to understand what this repo does

**Comment by User9684** [comment]
> discord notified the owner of every bot token listed here and automatically reset the tokens. So yeah, this list is pointless.

You are also pointless. You are a dull pencil. You are a circle.

**Comment by aerydev** [comment]
you damn idiot, he helped you, he finds discord tokens on replit and publishes them here so discord can detect it and revoke the token

**Comment by skidmaster69420** [comment]
Hello there,

It's been a few wild weeks! You may have noticed that I have been inactive, though that was only due to me playing the bestest games the market has to offer, like the critically acclaimed Persona 5 Royal... though I couldn't beat the tutorial, sadly. It's a little harder than Solitaire. Though I don't really understand what's about. But it has some pretty Anime Waifus, might collect their figurines into my collection. I recently have added a Asuna Figurine into my collection, the one with the spear! It's honestly pretty amazing!

Oh and I guess I should be responding to your "the list is pointless."
Well, your entire life is pointless.

Have a nice day!

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
