### ISSUE TITLE
bro why is my token bot here i made it for my friends and i 

### ISSUE THREAD

**Issue by MineConesFortress** [skidmaster69420/discord-tokens#48]
bruhhhh

**Comment by IMarkoMC** [comment]
> bro why is my token here

Your token was stored in plain text where everyone can find it and do whatever he wants with your bot token.

You should use [Environment variables](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env) to store secrets

**Comment by skidmaster69420** [comment]
Hello there,

so regarding that lawsuit I got from the Amazon Head of Delivery due to sending death threats.
My attorney, which I was granted by the court, decided to go against me. He's now also suing me. He was supposed to be my Defense Attorney but turned into the Prosecutor, that pissed the Prosecutor off and she became my Defense Attorney.
I feel like that isn't supposed to happen, but what can I do about it? Not like I have any chance in appealing their decision.

When a defense attorney turns prosecutor, does that mean that I am special? My teachers always did say that, but they also put me in Special ED. Which was fun, because I was insulted by everyone including the teachers... sorta like BOSS did... I do miss him somewhat, I guess.

Oh and also regarding the bot that you made for your friends, 
your friends in truth hate you, and put the bot on the list themselves.
I agree with your friends though, you are literal trash.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
