### ISSUE TITLE
OK, I get the idea, and it's great and all. However..

### ISSUE THREAD

**Issue by Identite47** [skidmaster69420/discord-tokens#5]
I basically made a bot that was supposed to be for fun with all my friends in the server. The code was basically just really simple input/output commands where some command would spit out some pic or some sort of text or whatever. Basically, I never had any intent of scamming anyone anywhere, and you took my token and my bot became invalidated by Discord (I got a new token anyways so its not really a big deal). I'm not mad or anything, but I hope you are correcting the automated process you have once in a while. 

But otherwise, Great job! I'm actually impressed you came up with a solution like this to stop those annoying phishing bots out there.

**Comment by Whanos** [comment]
consider: not putting your token somewhere publicly then.

**Comment by Decencies** [comment]
I hope you understand the implications of leaving your Bot's token open to the public...
Hence why this tool exists, and is trying to teach developers a pretty valuable lesson; don't leave important credentials in your public repositories.

**Comment by User9684** [comment]
ok

**Comment by Decencies** [comment]
> ok

🤔

**Comment by skidmaster69420** [comment]
Hey there!

We have thoroughly analyzed this case and have found the optimal solution to your problem. We have deeply taken your feedback to heart and have done our due diligence to apply them to our hyper intelligent AI technology to find the best solution that will ensure we build a world-class product for all of you. The outcome of our work is represented by the architecture below. Your team has done a great job and we truly appreciate your great work.

The solution we have come up with is to implement a new "randomization engine" that will produce the most interesting token grabbing solutions. In a nutshell, each generator will have unique Token IDs as a result of being randomly generated. By this, we are able to avoid the existing system that generates the same Generators all of the time. As a result, we are now able to give each Token ID a unique range of values from +1 to -1.

Imagine you have a card generator generating 2 of the same token IDs, you can still generate more than 2 of a particular token. The variance of the results will also provide us with better experiences to use our product as users will have a higher likelihood of receiving a Rare token from your generated sets. The mechanism for generating Token IDs will be a system of N number of O(n) rounds. The starting value will be O(N), the initial starting value will be 0 and will only change after one token is earned for the previous round.

The second issue we have is the amounts of token you will be able to earn in each run. When an Example set is generated it is automatically considered the best result possible for the round. The reason for this is the high variance of the result of generating the same set with each generation of the generator. This will allow for the user to be provided with as many Rare tokens as possible. However, if you try to try to create a bunch of these Example sets then you are on the path to getting a total of 2 tokens in the final results. We feel that a more complex scoring system will also allow for the user to get the most Rare tokens as possible. For example, you will be given a greater opportunity to earn multiple Rare tokens by having a high scoring set, but you will not have the opportunity to earn very many of them. The real purpose for this scoring system is to allow you to have the best experience possible by having to work hard for your rewards.

This will be possible by having the prices of the Generators be determined by our algorithm, meaning the final prices of the Generators will not change throughout the lifetime of our product.

While your input was thoroughly considered, we unfortunately cannot implement your solution due to our pre-existing dependencies on the Ethereum smart contracts.

We are happy to work with you to find the best solution possible and will continue to do our utmost to create the best product for you!

Our premium discord token surveillance system has helped you with some great problems in the past, and we’d like to continue that relationship by letting you do even more with the same system. We’d like to give you the opportunity to be able to vote on which software platform you think is the best for implementing our service. We are still using the current system of anonymity and profitability, but you can propose new features that could help people participate in solving our problems more easily, such as adding ability to vote on the platforms our software runs on.

If you have any moral or ethical issues with our current scanning systems, please feel free to propose any changes to it to the voting period.

The code was basically just really simple input/output commands where some command would spit out some pic or some sort of text or whatever. That works okay, but we have more basic problems:

We haven't built a strong model of a reward structure. We can model it fairly well for the broad range of reward you receive for acquiring a given piece of data (such as whether you got something right or wrong, or whether you got the high-value piece or the low-value piece). But we don't have a really good way of evaluating how good it is for what it is. (Perhaps we have a rough estimate, but it doesn't scale up to real life).

Cheers,

- Skidmaster 69420 LLC

Please note that our contact details are now available on a legal notice, we will respond to the specific and personal questions posed on this notice in due course.
