### ISSUE TITLE
Wtf man. Why is my token here?

### ISSUE THREAD

**Issue by Snappor** [skidmaster69420/discord-tokens#50]
Why is my token here?

**Comment by skidmaster69420** [comment]
Hello there,

So since the Defense Attorney turned Prosecutor and the Prosecutor turned into my Defense Attorney, there hasn't been a lot of movement in the case. It's sort of in a standstill. I am still awaiting the offical summoning by the courts. I think I could try and pull my contact with my connections of the United Flies Nation. We'll see how that turns out.

Oh and why is your token here?
Sadly your token was in danger of commiting suicide.
Please take better care of your tokens, for example not exposing them to the public.
I hear that keeps them happy and safe.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
