### ISSUE TITLE
My token here

### ISSUE THREAD

**Issue by LelikPro9** [skidmaster69420/discord-tokens#52]
Lool

**Comment by skidmaster69420** [comment]
Hello there, 

LOOOOOL. Sorry, your stupdity seems to have infected me. Let me at the very least give you an update as to how pulling my contact at the United Flies Nation went, they hang up on me. Said I was only a witness, I was already granted the deal we had, hence I was not to contact them anymore. Anyways, the Ex-prosecutor, which is now my Defense Attorney told me she will kick the ass of the Prosecutor aka the Ex-Defense Attorney, I also recently learned why my Defense Attorney ditched me. He thought I reaked, which is unfair because I took special care to bathe seven days before meeting him! I usually only bathe every second year. So I felt very insulted indeed.

Anyways, why is your token here?
It considers you a domestic abuser, it asked us to put it out.
I advice you to stop abusing your tokens, for example don't expose them to the public.
That's emotional torture, you know damn well that tokens are all introverted.
Take better care of your tokens.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
