### ISSUE TITLE
Discord Token

### ISSUE THREAD

**Issue by twobuilderstwotools** [skidmaster69420/discord-tokens#53]
I have been alerted that the token for our bot has been leaked here & Discord have reset the token.

**Comment by skidmaster69420** [comment]
Hello there,

So there has been a lot happening in the development of the trial, though it seems ever less like something connected to me. But rather some romantic feud between the defense attorney and the prosecutor, or actually to be more accurate the Ex-Prosecutor and the Ex-Defense Attorney which have both turnedcoat. I think this is illegal, but I don't know what to do about it. Anyway... the trial is set for a date next week, I am not anxious. Because I will be able to bribe the Judge with Cheese! 

Thank you for noticing that you have been alerted. 
This is also an alert regarding that alert. Which is an alert that was caused by that other alert!
IN FACT ANOTHER ALERT HAS OCCURED BECAUSE OF THAT ALERT.
YOU ARE CAUSING TOO MANY ALERTS TOO RING. SOON WE WON'T HAVE ANY LEFT!!
EVEN THE ALERTS FROM THE POLICE ARE NOW COMPROMISED FROM YOUR ALERTS.

> **Warning**
> THIS IS A WARNING CAUSED BY THE OTHER WARNINGS, THIS WARNING HAS BEEN SENT OVER THE SKIDMASTER GITHUB ACCOUNT, WARNING!
