### ISSUE TITLE
Damn. My discord bot token was stole i didn't even published it

### ISSUE THREAD

**Issue by naikio-offi** [skidmaster69420/discord-tokens#55]

**Comment by KingTino104** [comment]
your bot was hosted on replit

**Comment by skidmaster69420** [comment]
Hello there,

So the court date is rapidly approaching, I am still in the middle of preparing my outfit for that day.
For the suit, I choose a Panda Pajama. For the watch, I will wear one that screams "FUCK YOU STUPID JUDGE" every hour.
I won't turn that alarm off either. I will let that Judge hear that alarm every single time. 
My defense attorney had suggested me to wear a normal suit, but... I will ignore that bit of advice.
I will never EVER be normal and I know that. Though... I will also try and sneak a knife into the court.

If those stupid Jurys or Judges or whatever chooses to tell me I am "guilty", I will commit a british underground incident... for those that don't know, that's when you try and cut bread, but instead of bread it's human flesh! 

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
