### ISSUE TITLE
Tf did I ever do?

### ISSUE THREAD

**Issue by wadefield** [skidmaster69420/discord-tokens#57]
Bro, I do not understand what I did for my token to get uploaded, I see in your description you "get revenge on scammers" but I literally did nothing wrong, I just was having a normal day and got notified on my token being used but thankfully I resetted the token. Wtf bro..

**Comment by Chosey98** [comment]
That means someone already had your token so he saved you

**Comment by wadefield** [comment]
Okay?

>

**Comment by skidmaster69420** [comment]
Hello there,

I am glad that you see now, but what did you to cure your blindless? Did you steal someones eyes? I think that's an actual anime move and I am inspired, I will go on to take the eyes of 20 people I met today, you have just inspired me so much! I think that they may die if I take their eyes... But oh well! You have just inspired me so much. :)

Oh and the court date is tomorrow, aside from wearing a Pajama, wearing a watch that screams "FUCK YOU JUDGE", I will also try and smuggle a gun into the courtroom. You know, to just radiate that American spirit, so that the Judge will truly think of me as an pure blooded American. Maybe I will get a good sentence that way.

Thank you, time to commit murder!

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
