### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by KingTino104** [skidmaster69420/discord-tokens#58]
this is not an attack.
please read the readme for more info

**Comment by skidmaster69420** [comment]
Hello there,

so I could actually give you an update on the court date, but instead of that....

WHAT DO YOU MEAN THIS IS NOT AN ATTACK?
I WILL ATTACK EVERYONE ON THIS REPO. I WILL SEE TO IT THAT THEY SUFFER A TERRIBLE FATE.
I WILL SEE TO IT THAT THEY SHALL SUFFER FOR THE REST OF THEIR LIVES. I WILL MAKE CERTAIN THAT THEIR GRANDKIDS REGRET EVER EXISTING. I WILL HUNT THEM FOR THE REST OF THEIR REMAINING LIVES AND MAKE IT A LIVING HELL.
HOW DARE THEY EVER MAKE A ISSUE HERE, I WILL MAKE IT SO THAT THEY REGRET EVER EVER EVER CREATING A STUPID BOT. I WILL ATTEMPT TO SEEK OUT THEIR LOVED ONES AND TORTURE THEM AS WELL.

EARTH IS MY VICTIM. 

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
