### ISSUE TITLE
Why are you doing this kind of stuff??

### ISSUE THREAD

**Issue by exploringcomputerwithprashrey** [skidmaster69420/discord-tokens#60]
Why annoy.. learn manners

**Comment by genixlinux** [comment]
FAAAAAACS

**Comment by skidmaster69420** [comment]
Hello there,

So I uninstalled the Punjabi No Virus program. I think... yes, I did... nothing is happening. Anyway time to start the lecture.

"Why are you doing this kind of stuff?" So. I assume you are capable of writing in English, yes? Well I doubt that. Your sentence is indicating that the "stuff" is plural, yet in your sentence you are using "stuff" singular. Furthermore are you utilzing "this", which makes not a lot of sense. Honestly I believe you were going for "Why are you doing this?" noticed that I cut out "of stuff", well because your sentence as it is currently makes 0 sense. It honestly speaks of the intelligence you have, though in case you remind me... here's your IQ. IQ = -∞, that's right your IQ broke the scale. I don't know how, but you did.

On to the argument of your manners, you know I may have been arrested for bringing weaponary to a court, but you should be arrested for the attrocious English that you are selling as "normal" English. Honestly, go apologize to all the English Grammar Books that you have ever read, they are truly dissapointed in you, as am I. 

Also the manners that you speak of?
Well one of the most common manners is to say "please" when you ask for something.
But you didn't do that. 
So, let me allow to do it for you.

"Please go fuck yourself."

See, that sentence has manners. Unlike you. So go fuck yourself.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
