### ISSUE TITLE
this isnt really imprtant but

### ISSUE THREAD

**Issue by KyrensAttic** [skidmaster69420/discord-tokens#61]
lol thanks for taking my bad bots token, i dont use it anymore but still, this thing is taking other peoples tokens, so maybe this ain't the best idea?

**Comment by IMarkoMC** [comment]
"Taking" is not the best definition for what we do.

All the tokens in this repo are tokens that are publicly available in the internet so it's not "taking other peoples tokens".

If you want to host your bot in some free/public hosting please use ENV variables as anyone that finds your token can do whatever they want with your bot

**Comment by skidmaster69420** [comment]
>**Note**
**THIS GITHUB ACCOUNT HAS BEEN SEIZED BY THE FLY BUREAU OF INVESTIGATION**

>**Warning**

This account has been seized in order to investigate the individual known as Unpaid Intern, he appeared to court with heavy weaponry. Though he was arrested at the entry, investigation is now fully underway. It has been found that only Unpaid Intern was involved in this plot of his, hence no other individual has been arrested. Further information will soon follow.

Items that were confiscated:

- Ninja Stars

- A Nerf Gun with tacks at the tip of the projectiles.
- A watch which periodically sounded "FUCK THE JUDGE" every couple of minutes.
- Panda Pajamas
