### ISSUE TITLE
Sobre Questões Dos Tokens 

### ISSUE THREAD

**Issue by Lokinded** [skidmaster69420/discord-tokens#8]
Tudo Bem Que O Srs Fazem Isso Mais Chega até Me Atrabalgar Sobre Questões Dos Bots, acho Que As Pessoas Poderia Ter Cuidado Por Si Mesmo, até porque se elas não sofrerem ataque, não vão saber como se defender.
A vcs acho uma falta de respeito publicar token em rede sem permissão, mesmo fazendo pra me ajudar irei procurar fontes de direito descobrir quem tá por trás disso e errei abrir uma aquisição na justiça por danos a privacidade pública.

**Comment by Whanos** [comment]
"It's ok that you guys do this but it even bothers me about bot issues, i think people could be careful for themselves, because if they don't suffer attack, they won't know how to defend themselves.
I think it's a lack of respect for you to publish a token on the network without permission, even doing it to help me I will look for sources of law to find out who is behind it and I was wrong to open an acquisition in justice for damage to public privacy."

are you suggesting you're gonna sue us for invalidating a token you posted publicly

we did you a favour

**Comment by skidmaster69420** [comment]
Sadly every single sentence of this comment has caused multiple children in Africa brain damage. 
Consider donating to your local charity to remedy the damage you have caused. 

https://donate.unicef.org/donate/now/

Or consider a local alternative: https://www.globalgiving.org/projects/feed-and-educate-children-in-salvador-brazil/

Adeus
