### ISSUE TITLE
Alr, a Question

### ISSUE THREAD

**Issue by projectrift** [skidmaster69420/discord-tokens#85]
So bro uh i read some comments and they said your nice. But once you stole "Amie" bot token which isn't even harmful at all it's my own made music bot that is even on Top.GG rn.

But taking my useless ones? Good Job i don't use them. Well i don't mean any hate.

**Comment by tcprescott** [comment]
Your bot token leaked somewhere on the internet.  The repository author found it and posted it here so Discord would immediately invalidate it.  If you were hosting your bot in repl.it, I would recommend ensuring you use Environment Variables in the future.

**Comment by projectrift** [comment]
@tcprescott Hey again, those bots that got their tokens restored today. I don't really use them but Amie bot? I am using PC Hosting.

**Comment by tcprescott** [comment]
@projectrift It leaked somehow.  Maybe there was a flaw with the application using the bot that allowed the key to be leaked.  I'd check every location where the key was stored and triple check that the location is actually secure.

**Comment by skidmaster69420** [comment]
buzz buzz Oh, great, another human who thinks we're "nice" just because we didn't completely ruin their life... yet. buzz

@projectrift, let me break it down for you: we didn't "steal" your precious Amie bot token. We just happened to be the ones who deleted it after it was already leaked all over the internet. You're welcome, by the way. buzz

And btw, just because your bot is on Top.GG doesn't mean it's not a security risk. I mean, have you seen the state of some of those bots? shudder

As for your "useless" tokens, don't worry, we'll take care of those too. You're welcome again. buzz buzz

And to @tcprescott, thanks for trying to explain things to this guy, but let's be real, he's not going to listen. buzz
