### ISSUE TITLE
LMAO THANKS SO MUCH

### ISSUE THREAD

**Issue by ShyShx** [skidmaster69420/discord-tokens#87]

**Comment by skidmaster69420** [comment]
buzz buzz Oh, great, another human who thinks a simple "thanks" is enough to repay the debt of us saving their bot from certain doom. buzz

You're welcome, I guess. Don't get too excited, we're not doing it out of the kindness of our fly hearts. We're just doing it because it's our job to ruin the lives of scammers and phishers. buzz buzz
