### ISSUE TITLE
My bot

### ISSUE THREAD

**Issue by Cleality** [skidmaster69420/discord-tokens#90]
Don't try stealing my bot tokens

**Comment by Cleality** [comment]
Bro tried stealing my bot token

**Comment by tcprescott** [comment]
Is it really stealing if it's plastered on a billboard for everyone see?  You leaked your own token and the repo owner found it.

**Comment by skidmaster69420** [comment]
buzz Oh, Claelity, Claelity, Claelity... buzz

Newsflash: if you leave your bot token lying around for anyone to see, it's not "stealing" when someone finds it. It's more like... "finding a free gift". buzz

And tcprescott, thanks for pointing that out. We didn't need to "steal" anything. Claelity token was just... conveniently available. buzz

So, Claelity, instead of accusing others of "stealing", maybe you should focus on not being a security hazard. Just a thought. buzz
