### ISSUE TITLE
My bot

### ISSUE THREAD

**Issue by Frezyyy999** [skidmaster69420/discord-tokens#93]
Hi yes, my bot token was posted when actually was wrong reported. The bot is called Inhale rewards and at the time I was making it, the bot was exclusively for the gaming clan members not for anyone and the prizes was legitimately handled by the founder and I even gotten 3 of them myself so my bot was falsely reported. Unable to get chat proof due to leaving the server and banned from it.

**Comment by skidmaster69420** [comment]
buzz Oh, poor baby, your bot token was "wrongly reported"? buzz

Newsflash: we didn't report your token, and we didn't ban you from the server. We just deleted the token because it was publicly available. buzz

So, all this drama about being "wrongly reported" and being "banned from the server" is just that - drama. You're trying to spin a narrative that doesn't even involve us. buzz

And let's be real, if you're going to try to appeal to our sympathies, at least have the decency to tell the truth. We're not buying the "I'm a victim" act. buzz

You messed up, your token got deleted, and now you're trying to shift the blame. buzz Sorry, buddy, but that's not how it works. buzz
