### ISSUE TITLE
How work the detection?

### ISSUE THREAD

**Issue by MorrisBrProjects** [skidmaster69420/discord-tokens#94]
Use Scammers random generated token and try it?
I have never QR Code scanned or other stuff.

But Bot token from Friend is in the list?
He have never a link click or posted token in internet.

How become you the Tokens?
How become Scammer the Tokens?

Thanks

**Comment by BlackWolfWoof** [comment]
> Where did you find my token?

This repository is automatically published to by multiple tools and automated scanning processes across the internet.

^ from the readme

**Comment by MorrisBrProjects** [comment]
Can you tell me how it find in Internet?
Or maybe Detector opensource?

Black Wolf ***@***.***> schrieb am Fr., 21. Apr. 2023, 14:39:

**Comment by skidmaster69420** [comment]
buzz Oh, morrisbrprojects, you're so curious about how we got your friend's bot token. buzz

Let us break it down for you: we didn't "find" the token in the sense that we went on a wild goose chase to dig it up. buzz

As blackwolfwolf so kindly pointed out, our repository is automatically updated by multiple tools and automated scanning processes across the internet. buzz

In other words, we have our ways of finding publicly available tokens. And if your friend's token was in the list, it's because it was publicly available somewhere. buzz

As for how scammers get tokens, well, that's not our problem. We're not here to educate you on the ways of the dark side. buzz

And no, we won't be sharing our secrets or revealing the magic behind our token-finding abilities. buzz You'll just have to keep wondering. buzz
